make ; rm ./resources/players/gthomas.filler ; cp ./gthomas.filler ./resources/players/ ;
./resources/filler_vm -f ./resources/maps/map00 -p1 ./resources/players/gthomas.filler -p2 ./resources/players/abanlin.filler -q ;
./resources/filler_vm -f ./resources/maps/map00 -p1 ./resources/players/gthomas.filler -p2 ./resources/players/abanlin.filler -q ;
./resources/filler_vm -f ./resources/maps/map00 -p1 ./resources/players/gthomas.filler -p2 ./resources/players/abanlin.filler -q ;
./resources/filler_vm -f ./resources/maps/map00 -p1 ./resources/players/gthomas.filler -p2 ./resources/players/abanlin.filler -q ;
./resources/filler_vm -f ./resources/maps/map00 -p1 ./resources/players/gthomas.filler -p2 ./resources/players/abanlin.filler -q ;
./resources/filler_vm -f ./resources/maps/map00 -p1 ./resources/players/gthomas.filler -p2 ./resources/players/carli.filler -q ;
./resources/filler_vm -f ./resources/maps/map00 -p1 ./resources/players/gthomas.filler -p2 ./resources/players/carli.filler -q ;
./resources/filler_vm -f ./resources/maps/map00 -p1 ./resources/players/gthomas.filler -p2 ./resources/players/carli.filler -q ;
./resources/filler_vm -f ./resources/maps/map00 -p1 ./resources/players/gthomas.filler -p2 ./resources/players/carli.filler -q ;
./resources/filler_vm -f ./resources/maps/map00 -p1 ./resources/players/gthomas.filler -p2 ./resources/players/carli.filler -q ;
./resources/filler_vm -f ./resources/maps/map00 -p1 ./resources/players/gthomas.filler -p2 ./resources/players/grati.filler -q ;
./resources/filler_vm -f ./resources/maps/map00 -p1 ./resources/players/gthomas.filler -p2 ./resources/players/grati.filler -q ;
./resources/filler_vm -f ./resources/maps/map00 -p1 ./resources/players/gthomas.filler -p2 ./resources/players/grati.filler -q ;
./resources/filler_vm -f ./resources/maps/map00 -p1 ./resources/players/gthomas.filler -p2 ./resources/players/grati.filler -q ;
./resources/filler_vm -f ./resources/maps/map00 -p1 ./resources/players/gthomas.filler -p2 ./resources/players/grati.filler -q ;
./resources/filler_vm -f ./resources/maps/map00 -p1 ./resources/players/gthomas.filler -p2 ./resources/players/hcao.filler -q;
./resources/filler_vm -f ./resources/maps/map00 -p1 ./resources/players/gthomas.filler -p2 ./resources/players/hcao.filler -q ;
./resources/filler_vm -f ./resources/maps/map00 -p1 ./resources/players/gthomas.filler -p2 ./resources/players/hcao.filler -q ;
./resources/filler_vm -f ./resources/maps/map00 -p1 ./resources/players/gthomas.filler -p2 ./resources/players/hcao.filler -q ;
./resources/filler_vm -f ./resources/maps/map00 -p1 ./resources/players/gthomas.filler -p2 ./resources/players/hcao.filler -q ;
./resources/filler_vm -f ./resources/maps/map00 -p1 ./resources/players/gthomas.filler -p2 ./resources/players/superjeannot.filler -q ;
./resources/filler_vm -f ./resources/maps/map00 -p1 ./resources/players/gthomas.filler -p2 ./resources/players/superjeannot.filler -q ;
./resources/filler_vm -f ./resources/maps/map00 -p1 ./resources/players/gthomas.filler -p2 ./resources/players/superjeannot.filler -q ;
./resources/filler_vm -f ./resources/maps/map00 -p1 ./resources/players/gthomas.filler -p2 ./resources/players/superjeannot.filler -q ;
./resources/filler_vm -f ./resources/maps/map00 -p1 ./resources/players/gthomas.filler -p2 ./resources/players/superjeannot.filler -q ;
./resources/filler_vm -f ./resources/maps/map00 -p1 ./resources/players/abanlin.filler -p2 ./resources/players/gthomas.filler -q ;
./resources/filler_vm -f ./resources/maps/map00 -p1 ./resources/players/abanlin.filler -p2 ./resources/players/gthomas.filler -q ;
./resources/filler_vm -f ./resources/maps/map00 -p1 ./resources/players/abanlin.filler -p2 ./resources/players/gthomas.filler -q ;
./resources/filler_vm -f ./resources/maps/map00 -p1 ./resources/players/abanlin.filler -p2 ./resources/players/gthomas.filler -q ;
./resources/filler_vm -f ./resources/maps/map00 -p1 ./resources/players/abanlin.filler -p2 ./resources/players/gthomas.filler -q ;
./resources/filler_vm -f ./resources/maps/map00 -p1 ./resources/players/carli.filler -p2 ./resources/players/gthomas.filler -q ;
./resources/filler_vm -f ./resources/maps/map00 -p1 ./resources/players/carli.filler -p2 ./resources/players/gthomas.filler -q ;
./resources/filler_vm -f ./resources/maps/map00 -p1 ./resources/players/carli.filler -p2 ./resources/players/gthomas.filler -q ;
./resources/filler_vm -f ./resources/maps/map00 -p1 ./resources/players/carli.filler -p2 ./resources/players/gthomas.filler -q ;
./resources/filler_vm -f ./resources/maps/map00 -p1 ./resources/players/carli.filler -p2 ./resources/players/gthomas.filler -q ;
./resources/filler_vm -f ./resources/maps/map00 -p1 ./resources/players/grati.filler -p2 ./resources/players/gthomas.filler -q;
./resources/filler_vm -f ./resources/maps/map00 -p1 ./resources/players/grati.filler -p2 ./resources/players/gthomas.filler -q;
./resources/filler_vm -f ./resources/maps/map00 -p1 ./resources/players/grati.filler -p2 ./resources/players/gthomas.filler -q;
./resources/filler_vm -f ./resources/maps/map00 -p1 ./resources/players/grati.filler -p2 ./resources/players/gthomas.filler -q;
./resources/filler_vm -f ./resources/maps/map00 -p1 ./resources/players/grati.filler -p2 ./resources/players/gthomas.filler -q;
./resources/filler_vm -f ./resources/maps/map00 -p1 ./resources/players/hcao.filler -p2 ./resources/players/gthomas.filler -q;
./resources/filler_vm -f ./resources/maps/map00 -p1 ./resources/players/hcao.filler -p2 ./resources/players/gthomas.filler -q;
./resources/filler_vm -f ./resources/maps/map00 -p1 ./resources/players/hcao.filler -p2 ./resources/players/gthomas.filler -q;
./resources/filler_vm -f ./resources/maps/map00 -p1 ./resources/players/hcao.filler -p2 ./resources/players/gthomas.filler -q;
./resources/filler_vm -f ./resources/maps/map00 -p1 ./resources/players/hcao.filler -p2 ./resources/players/gthomas.filler -q;
./resources/filler_vm -f ./resources/maps/map00 -p1 ./resources/players/superjeannot.filler -p2 ./resources/players/gthomas.filler -q ;
./resources/filler_vm -f ./resources/maps/map00 -p1 ./resources/players/superjeannot.filler -p2 ./resources/players/gthomas.filler -q ;
./resources/filler_vm -f ./resources/maps/map00 -p1 ./resources/players/superjeannot.filler -p2 ./resources/players/gthomas.filler -q ;
./resources/filler_vm -f ./resources/maps/map00 -p1 ./resources/players/superjeannot.filler -p2 ./resources/players/gthomas.filler -q ;
./resources/filler_vm -f ./resources/maps/map00 -p1 ./resources/players/superjeannot.filler -p2 ./resources/players/gthomas.filler -q ;
